### PR TITLE
Use CCM::TextRender instead of CAF::TextRender in RegexpTest

### PR DESCRIPTION
**Pull request by stdweird**
Use CCM::TextRender instead of CAF::TextRender in RegexpTest; the unittests now can also test with element instances.

Some other minor related modifications
 * a convenience method `set_json_typed` to enable `json_typed` (together with a `get_json_typed` to check the current setting)
 * an advanced option to overrride the module and contentspath via regexptest flags (useful to test rendering of the `/`-element); but this should considered an exception.

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha this needs https://github.com/quattor/CCM/pull/51 to pass the tests, is based on https://github.com/quattor/maven-tools/pull/52 and is a requirement for https://github.com/quattor/configuration-modules-core/pull/475

i'm also tagging this 15.4

**Comment by stdweird** [comment]
test this please

**Comment by jouvin** [comment]
@stdweird I have the feeling that some of the commits are related to json type support not really to `CCM:TextRender`. Am I write? In this case, it would be good to adjust the title of the PR...

Also, it would be good to have a short description of the goal of the PR... Not really obvious without an explanation! (I have no doubt it is useful)

Else LGTM.

**Comment by stdweird** [comment]
@jouvin i updated the PR description. i'm afraid that it will only become really clear why this is relevant when i update https://github.com/quattor/CAF/pull/84 with the `CCM::TextRender` features that are part of 15.4

the `json_typed` fixes are relevant for any testing which requires typed data, which requires `CCM::TextRender`.

**Pull request merged**
