### PR TITLE
Test::Quattor::Object log history

### PR DESCRIPTION
**Pull request by stdweird**
Keep track of logging activity to check if logging happens as intended (e.g. error is logged when failure condition is triggered).

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha i tagged this for 15.4, since it's needed for some development work for 15.6. but it is not required for 15.4, so i'll leave it up to you (i can continue without it)

**Comment by jrha** [comment]
I'm happy with it going into 15.4, could you correct the multiple typos in the commit message and expand upon what it is intended to do in the PR text though?

**Comment by jrha** [comment]
Also something explaining why this came about would be nice.

**Comment by stdweird** [comment]
@jouvin thanks for ponting it out. rebased it on master

**Pull request merged**
