### PR TITLE
RegexpTest block separator should include newline

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by ned21** [comment]
LGTM

**Comment by jrha** [comment]
@stdweird Presumably this needs a new release of the tools?

**Comment by stdweird** [comment]
@jrha yes, new release is required. thanks.

**Comment by jrha** [comment]
@stdweird, the new release (1.45) is built and should be available soon.
See http://search.maven.org/#search|ga|1|org.quattor.maven

**Comment by stdweird** [comment]
@jrha thanks!

**Pull request merged**
