### PR TITLE
Mock reporter

### LINKED ISSUE #74: mock the reporter such that undef messages cause a failed test
See https://github.com/quattor/CAF/issues/134 and https://github.com/quattor/CAF/pull/135

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #74

### CODE REVIEW

**Comment by stdweird** [comment]
I'm running more tests on the repos, so far so good

**Comment by stdweird** [comment]
@jouvin there is one now :smile:

**Comment by jouvin** [comment]
LGTM. But what will be the impact on the testing of `CAF::Reporter` itself? I've the feeling that none (as it will be called by the mocked version) but I'm asking to be sure...

**Comment by stdweird** [comment]
the `CAF::Reporter` unittests do not use `Test::Quattor`, so this is not an issue
but i found some other problem, altough it looks unrelated

**Comment by stdweird** [comment]
Together with #75 and https://github.com/quattor/CCM/pull/82, unittests for CAF, CCM and modules-core pass.

**Pull request merged**
