### PR TITLE
ProfileCache: use compiled profile directly instead of downloading

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha this reduces the output in verbose mode of the unittests a lot. how long would it take to make an 1.56 release?

**Comment by jrha** [comment]
Not particularly long, but would require current masters to pass tests. Last night's CentOS 6 & 7 builds failed on the same problem:
```
CentOS 6: MVN E: # Failed test 'Same file, same data, so contents not changed, NoAction set'
CentOS 6: MVN E: # at src/test/perl/quattor_mock.t line 39.
CentOS 6: MVN E: # Failed test 'no diff on FileEditor open/close'
CentOS 6: MVN E: # at src/test/perl/quattor_mock.t line 78.

CentOS 7: MVN E: # Failed test 'Same file, same data, so contents not changed, NoAction set'
CentOS 7: MVN E: # at src/test/perl/quattor_mock.t line 39.
CentOS 7: MVN E: # Failed test 'no diff on FileEditor open/close'
CentOS 7: MVN E: # at src/test/perl/quattor_mock.t line 78.
```

**Comment by stdweird** [comment]
@jrha what CAF version is used for those?

**Comment by jrha** [comment]
It's just `build_all_repos` ... so master?

Full log is here:
https://github.com/quattor/release/releases/download/nightly_2017-12-06T14/build.log.gz

**Comment by stdweird** [comment]
ah, ok. i'll have a look

**Comment by jrha** [comment]
Thanks

**Comment by stdweird** [comment]
can you confirm that these hosts have selinux enabled? that's the only thing i can see from the logs that might be relevant

**Comment by stdweird** [comment]
ok, the jenkins master builds were not triggered in months, ie all unittests run with 17.3 (incl caf and ccm)

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
@jrha ok, jenkins fails again

**Comment by jrha** [comment]
Eew

**Comment by stdweird** [comment]
@jrha jenkins issue understood, waiting for merge to see it in action

**Comment by stdweird** [comment]
i can reproduce it locally, i was missing https://github.com/quattor/CAF/pull/262 in my local install

**Comment by stdweird** [comment]
@jrha last commits needs unittests and testing on all other repos, but it's the culprit

**Comment by stdweird** [comment]
@jrha unittests added. this is very likely to become 1.56. i'm going to test this on the repos now

**Comment by stdweird** [comment]
looks ok for caf, ccm, ncm-ncd
aii gives a failing test due to some spurious reporting, will be fix when bumping to 1.56
i have not tried any components yet, but i feel confident (or lucky 😄

**Comment by jrha** [comment]
Looking good, let me know when you are happy for this to be merged.

**Comment by jrha** [comment]
In the mean time I'll try to put together an environment when I can produce a new release of the build tools.

**Comment by stdweird** [comment]
@jrha i'm happy

**Comment by jrha** [comment]
@stdweird 1.56 released, should show up on Nexus at some point today.

**Pull request merged**
