### PR TITLE
Add Test::Quattor::Doc for documentation testing

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
Would be nice to have in a new release and all pom.xml bumped for 15.4 (that way people can start using them by 15.6)

**Comment by jrha** [comment]
Are there any tests for invalid pod?

**Comment by stdweird** [comment]
no, because `Test::POD` runs the tests (unless i mock the `Test` framework, hmmmm, actually,... i'll try to to just that later today)

**Comment by stdweird** [comment]
@jrha unittest for invalid pod files added

**Comment by jrha** [comment]
Nice.

**Comment by jrha** [comment]
LGTM

**Pull request merged**
