### PR TITLE
Test::Quattor::NoAction: set NoAction independent of the CAF::Object::NoAction

### PR DESCRIPTION
**Pull request by stdweird**
Allows you run test with `CAF::Object::NoAction` disabled (i.e. like in real usage), but without actually creating/editing files during the tests.

### CODE REVIEW

**Comment by ned21** [comment]
Can you split the whitespace clean up into a separate commit please?

**Comment by stdweird** [comment]
@ned21 done

**Comment by jrha** [comment]
LGTM

**Comment by stdweird** [comment]
@jrha i'm not sure how formulate this, but some components have logic handling `NoAction` (via `CAF::Object::NoAction`, but to test thi slogic, you still want all file operation mocked).

**Pull request merged**
