### PR TITLE
Test::Quattor::Critic: add Perl::Critic whitelist testing

### PR DESCRIPTION
**Pull request by stdweird**
Also adds an informational `perltidy` test
Requires #114

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha and you thought #112 would cause lots of work 😁

**Comment by stdweird** [comment]
also, please don't make any comments on what we should add and what not. if you want certain tests, open a PR, set a milestone and check your agenda when you have time fix the fallout

**Comment by jrha** [comment]
:see_no_evil:

**Comment by stdweird** [comment]
The perltidy test is way too difficult to tune, and perltidy has no support for whitelisting. You are advised to look at the output and we should discuss final parameters and possible impact in followup PRs

**Pull request merged**
