### PR TITLE
Package build-scripts as standalone Test::Quattor

### PR DESCRIPTION
**Pull request by stdweird**
So you can run unit tests without maven.

### CODE REVIEW

**Comment by stdweird** [comment]
@jouvin do you have any idea how to let the pm.xml packge the pod files and the .pl scripts. I added a block of maven magic in comment, but i can't make it work.

**Comment by stdweird** [comment]
@ned21 should allow to run unittests without mvn (tested on CCM and ncm-metaconfig) ( @gombasg once said that this is an issue for MS; so no more excuses not to add tests :smiling_imp: )
main issue is that i can't figure out how to add the `.pl` scripts or the pods to the rpm.

and to be clear: the jenkins tests and the release procedure should keep on using maven for testing

**Comment by ned21** [comment]
Given that I am currently battling against maven trying to add a new .pan file to a test suite, this is welcome. :-) How do I use it? I think mvnprove.pl needs a synopsis/usage and an addition to README please?

**Comment by stdweird** [comment]
@ned21 depends a bit where you want to use it. for the components there's a PR open https://github.com/quattor/configuration-modules-core/pull/730 (that can already be merged, it works with current build-tools), and then you need to the package and install this branch to get Test::Quattor. i'll PM you an rpm

wrt your issue, open an issue about it, i don't know what you are trying to do, but adding tests should be straightforward (and won't be any different with this).

also, i plan to convert https://github.com/stdweird/maven-tools/blob/getting_started/Getting_started.md in a post for the website and show it during the workshop; if you have any questions or want to see things clarified, now's the time

**Comment by ned21** [comment]
@stdweird Thanks - I realised the error was that I had made a copy of simple.pan and then failed to update the template line. :( I'll file the suppression of the compile errors as an issue.

**Comment by stdweird** [comment]
@jrha rebased

**Pull request merged**
