### PR TITLE
Support template unittesting through controlled failure of compilations

### PR DESCRIPTION
**Pull request by stdweird**
Support controlled pan compilation failure through ProfileCache prepare_profile_cache method.
This allows unittesting of failing pan templates (eg to unittest intentional compilation failures due to schema violation).

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha i think last commit closes another (hopefully last) possible path that can lead to a racecondition and the `DESTROY` failures of the unittests

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
test this please

**Comment by jrha** [comment]
@stdweird — I'm happy to merge this when the PR has a suitable bit of text explaining what this is and why it's needed. :smile_cat:

**Comment by stdweird** [comment]
@jrha i thought the original "Text explaining what this means goes here." was clear enough :smile:

**Comment by jrha** [comment]
Thanks.
Does this also fix quattor/configuration-modules-core#432?

**Comment by stdweird** [comment]
@jrha remains to be seen, but very likely.

**Comment by jrha** [comment]
Ok cool

**Comment by jouvin** [comment]
I propose to merge this PR now in order to produce a new release. @jhra, anything against merging?

**Pull request merged**
