### PR TITLE
Tidy and Critic should not check pod files

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha ideally, this gets merge and a release is made (for maven; making an rpm as part of the release is not needed atm). i'm testing `ncm-ncd` atm, it's very useful

**Comment by stdweird** [comment]
@ned21 we have quite a bit code that does not use `Test::Quattor` to do actual non-mocked testing (in particular, `CAF` can't use it). but it should always be non-disruptive to import `Test::Quattor::Object` in existing tests to enable the warning test.

**Comment by ned21** [comment]
@stdweird thanks for the explanation. Apologies I actually seem to have copy & pasted the wrong commit id. It was 85c9e66 (critic and tidy codedirs default to doc poddirs) that I didn't understand.

**Comment by stdweird** [comment]
as we have most of the pod either in the scripts and/or modules, or have pod file in the directory as the code; the checks typically scan the same directories for code to check. so instead of configuring it 3 times with the same value, we can do so using one value. the doc directory is chosne because we currently have pod tests with the list of dirs.

eg https://github.com/quattor/maven-tools/blob/master/build-scripts/src/test/perl/00-tqu.t#L12
i should remove the codedirs value in the critic and tidy section.

**Comment by ned21** [comment]
OK. Since 16.12 is done and @jrha is on holiday, should this get merged or wait for @jrha ?

**Comment by stdweird** [comment]
@ned21 i don't think 16.12 is out, but maven-tools doesn't follow the releases anyway
i also pushed and squashed a commit fixing the redundant codedir entries in the 00-tqu unittest.

**Pull request merged**
