### PR TITLE
Allow builds to succeed even if javadoc doclint fails

### PR DESCRIPTION
**Pull request by jrha**
* Reformat pom files with xmllint in utf-8 mode for consistency.
* Disable doclint to allow builds with JDK 1.8+.
  In JDK 1.8+ doclint errors cause the build to fail, this restores the more tolerant behaviour.

This change requires JDK 1.8+.

### CODE REVIEW

**Comment by jrha** [comment]
@stdweird merge this and I'll build 1.58

**Comment by ned21** [comment]
> In JDK 1.8+ doclint errors cause the build to fail, this restores the more tolerant behaviour.
Presumably at some point in the future this will become a hard error? Is it worth opening an issue recording which docs in what codebase need updating for easy future reference?

**Comment by jrha** [comment]
@ned21 this was the point in the future that it became a hard error and the Java community reacted quite negatively (e.g. http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html), from what I can see some of the "errors" are Maven tags that doclint just doesn't understand.

**Comment by jrha** [comment]
I'm going to merge this so I can build 1.58 and progress with the rest of the release, we can try other options later if need be.

**Pull request merged**
